name: Create Release

on: release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2.3.4
    - name: Create artifact
      uses: montudor/action-zip@v0.1.1
      with:
        args: zip -qq -r JAVLibrary.bundle.zip ./ -x ./.github/ ./.gitattributes ./.gitignore ./README.md
    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: JAVLibrary.bundle
        path: JAVLibrary.bundle.zip
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: JAVLibrary.bundle.zip
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
